package dev.spectroscope.core.image;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.spectroscope.core.events.RunEvent;
import dev.spectroscope.core.tools.Tool;

import java.util.function.Supplier;

/**
 * The {@code generate_image} tool: prompt in, cloud image out, bytes into the
 * content-addressed {@link ImageStore}, and an {@code image_generated} event
 * through the context's emit sink — the UIs render the gallery from that event,
 * the model only ever sees the short result string.
 *
 * <p>The provider arrives as a {@link Supplier} because the web UI can switch
 * providers mid-session; each call fetches the current one.</p>
 */
public final class GenerateImageTool implements Tool {

    private static final ObjectMapper JSON = new ObjectMapper();

    private final Supplier<ImageProvider> provider;
    private final ImageStore store;

    /**
     * Wires the tool to its provider source and blob store.
     *
     * @param provider resolved fresh on every call, so a mid-session provider switch takes effect
     * @param store    content-addressed sink the generated bytes land in
     */
    public GenerateImageTool(Supplier<ImageProvider> provider, ImageStore store) {
        this.provider = provider;
        this.store = store;
    }

    /** The fixed name the model calls this tool by. */
    @Override
    public String name() {
        return "generate_image";
    }

    /** Model-facing description — it also steers the model away from re-reading the stored file. */
    @Override
    public String description() {
        return "Generates an image from a text prompt. The finished image is shown to the "
                + "user in the gallery panel automatically - do not try to read or open the file.";
    }

    /** A single required string property: {@code prompt}. */
    @Override
    public JsonNode inputSchema() {
        ObjectNode schema = JSON.createObjectNode();
        schema.put("type", "object");
        ObjectNode properties = JSON.createObjectNode();
        properties.set("prompt", JSON.createObjectNode().put("type", "string"));
        schema.set("properties", properties);
        schema.set("required", JSON.createArrayNode().add("prompt"));
        return schema;
    }

    /** A paid cloud call — the human stays in the loop, same reasoning as {@code run_command}. */
    @Override
    public boolean needsPermission() {
        return true;
    }

    /**
     * Generates, stores, and announces one image: resolves the current provider (an
     * unset API key degrades to a readable error), writes the bytes to the store,
     * emits {@code image_generated} for the gallery, and returns a short summary —
     * the model never sees the payload.
     *
     * @param input   tool arguments — {@code prompt} is the only field read
     * @param context carries the agent/call ids and the emit sink for the gallery event
     * @return a one-line success summary, or an {@code ERROR: ...} string the model can act on
     */
    @Override
    public String execute(JsonNode input, ToolContext context) {
        String prompt = input.path("prompt").asText().strip();
        if (prompt.isBlank()) {
            return "ERROR: generate_image needs a non-empty prompt.";
        }

        ImageProvider imageProvider;
        try {
            imageProvider = provider.get();
        } catch (IllegalStateException missingKey) {
            // Typically an unset API key — the message already names the variable.
            return "ERROR: " + missingKey.getMessage();
        }

        try {
            ImageProvider.Generated generated = imageProvider.generate(prompt);
            ImageStore.Ref ref = store.put(generated.bytes(), generated.mediaType());
            context.emit().accept(new RunEvent.ImageGenerated(
                    context.agentId(), context.callId(), prompt,
                    imageProvider.providerName(), imageProvider.model(),
                    generated.mediaType(), ref.blobPath(), ref.sha256(),
                    System.currentTimeMillis()));
            long kiloBytes = Math.max(1, Math.round(generated.bytes().length / 1024.0));
            return "Image generated with " + imageProvider.providerName()
                    + " (" + imageProvider.model() + "): " + ref.blobPath()
                    + " (" + generated.mediaType() + ", " + kiloBytes + " KB). "
                    + "The user sees it in the gallery panel.";
        } catch (RuntimeException failure) {
            return "ERROR: image generation failed: " + failure.getMessage();
        }
    }
}
