package dev.spectroscope.server.playbooks;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * The documentation page of the bundled playbook is generated by
 * {@code scripts/build_playbook_docs.py} and committed. This test builds the
 * page into two fresh folders, requires the two builds to be byte identical,
 * and requires the committed page to equal the fresh build, so an edited
 * {@code playbook.json} (or LICENSE, or PROVENANCE.md) without a rebuild goes
 * red, the same pattern as the config doc drift test.
 */
class PlaybookDocsDriftTest {

    private static final String[] INPUTS = {"playbook.json", "LICENSE", "PROVENANCE.md"};
    private static final ObjectMapper JSON = new ObjectMapper();

    private static Path root;
    private static Path script;
    private static Path bundle;

    @BeforeAll
    static void locate() {
        for (Path candidate = Path.of("").toAbsolutePath();
                candidate != null; candidate = candidate.getParent()) {
            if (Files.isRegularFile(candidate.resolve("settings.gradle.kts"))) {
                root = candidate;
                break;
            }
        }
        assertTrue(root != null, "settings.gradle.kts not found above " + Path.of("").toAbsolutePath());
        script = root.resolve("scripts/build_playbook_docs.py");
        bundle = root.resolve("spectro-server/src/main/resources/bundled-playbooks/spectro");
    }

    private static boolean python3Present() {
        try {
            Process p = new ProcessBuilder("python3", "--version").redirectErrorStream(true).start();
            p.getInputStream().readAllBytes();
            return p.waitFor(30, TimeUnit.SECONDS) && p.exitValue() == 0;
        } catch (IOException | InterruptedException e) {
            return false;
        }
    }

    /** Copies the three inputs of the page into a fresh folder and returns it. */
    private static Path freshFolder(Path parent, String name) throws IOException {
        Path folder = Files.createDirectories(parent.resolve(name));
        for (String input : INPUTS) {
            Files.copy(bundle.resolve(input), folder.resolve(input));
        }
        return folder;
    }

    private record Run(int exit, String output) {}

    private static Run build(Path folder) throws IOException, InterruptedException {
        Process p = new ProcessBuilder("python3", script.toString(), folder.toString())
                .directory(root.toFile()).redirectErrorStream(true).start();
        String out = new String(p.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        assertTrue(p.waitFor(60, TimeUnit.SECONDS), "the builder did not finish in 60 seconds");
        return new Run(p.exitValue(), out);
    }

    @Test
    void twoBuildsAreByteIdentical(@TempDir Path tmp) throws Exception {
        assumeTrue(python3Present(), "python3 is not installed");
        assertTrue(Files.isRegularFile(script), "missing " + script);
        Path first = freshFolder(tmp, "first");
        Path second = freshFolder(tmp, "second");
        Run a = build(first);
        Run b = build(second);
        assertEquals(0, a.exit(), a.output());
        assertEquals(0, b.exit(), b.output());
        assertArrayEquals(Files.readAllBytes(first.resolve("docs/index.html")),
                Files.readAllBytes(second.resolve("docs/index.html")),
                "two builds of the same playbook differ");
    }

    @Test
    void theCommittedPageEqualsAFreshBuild(@TempDir Path tmp) throws Exception {
        assumeTrue(python3Present(), "python3 is not installed");
        assertTrue(Files.isRegularFile(script), "missing " + script);
        Path committed = bundle.resolve("docs/index.html");
        assertTrue(Files.isRegularFile(committed),
                "docs/index.html is not committed; run python3 scripts/build_playbook_docs.py " + bundle);
        Path folder = freshFolder(tmp, "fresh");
        Run run = build(folder);
        assertEquals(0, run.exit(), run.output());
        assertArrayEquals(Files.readAllBytes(folder.resolve("docs/index.html")),
                Files.readAllBytes(committed),
                "docs/index.html is out of date; run python3 scripts/build_playbook_docs.py " + bundle);
    }

    @Test
    void thePageCarriesTheWholePlaybook(@TempDir Path tmp) throws Exception {
        assumeTrue(python3Present(), "python3 is not installed");
        Path folder = freshFolder(tmp, "content");
        Run run = build(folder);
        assertEquals(0, run.exit(), run.output());
        String page = Files.readString(folder.resolve("docs/index.html"), StandardCharsets.UTF_8);
        JsonNode playbook = JSON.readTree(Files.readString(bundle.resolve("playbook.json")));

        assertTrue(page.contains("<title>" + playbook.get("name").asText() + "</title>"), "title");
        assertTrue(page.contains("<svg"), "inline graph");
        assertTrue(page.contains("prefers-color-scheme: dark"), "dark theme block");
        assertTrue(page.contains("--bg"), "colours come from custom properties");

        int steps = 0;
        int decisions = 0;
        for (JsonNode node : playbook.get("nodes")) {
            String name = node.has("name") ? node.get("name").asText() : node.get("id").asText();
            assertTrue(page.contains(">" + name + "<") || page.contains(name), "node " + name);
            String kind = node.get("kind").asText();
            if (kind.equals("step")) {
                steps++;
                assertTrue(page.contains("id=\"step-" + node.get("id").asText() + "\""), "step section " + name);
                for (JsonNode skill : node.get("skills")) {
                    assertTrue(page.contains(skill.asText()), "skill " + skill.asText());
                }
            } else if (kind.equals("decision")) {
                decisions++;
                assertTrue(page.contains("id=\"decision-" + node.get("id").asText() + "\""), "decision section " + name);
                if (node.has("max_rounds")) {
                    assertTrue(page.contains("up to " + node.get("max_rounds").asInt() + " rounds"),
                            "ceiling of " + name);
                }
            }
        }
        assertTrue(steps > 0 && decisions > 0);
        playbook.get("documents").fieldNames().forEachRemaining(id ->
                assertTrue(page.contains("id=\"document-" + id + "\""), "document section " + id));
        assertTrue(page.contains("Jesse Vincent"), "licence");
        assertTrue(page.contains("spectropowers:brainstorming"), "provenance");
    }

    @Test
    void thePageNeedsNoNetworkAndUsesNoDashPunctuation(@TempDir Path tmp) throws Exception {
        assumeTrue(python3Present(), "python3 is not installed");
        Path folder = freshFolder(tmp, "plain");
        assertEquals(0, build(folder).exit());
        String page = Files.readString(folder.resolve("docs/index.html"), StandardCharsets.UTF_8);
        assertFalse(page.contains("src=\"http"), "no remote script or image");
        assertFalse(page.contains("href=\"http"), "no remote stylesheet");
        assertFalse(page.contains("@import"), "no remote import");
        assertFalse(page.contains("—"), "no em dash");
        assertFalse(page.contains("–"), "no en dash");
    }

    @Test
    void aFolderWithoutAPlaybookFileIsRefused(@TempDir Path tmp) throws Exception {
        assumeTrue(python3Present(), "python3 is not installed");
        Run run = build(Files.createDirectories(tmp.resolve("empty")));
        assertNotEquals(0, run.exit(), "an empty folder must not produce a page");
        assertFalse(Files.exists(tmp.resolve("empty/docs/index.html")));
    }
}
