#!/usr/bin/env bash
# SearXNG's settings file, generated once on this machine.
#
# Two things have to be in it before the container is worth starting, and the
# image supplies neither:
#
#   secret_key        SearXNG refuses to boot on the placeholder it ships with,
#                     so the key is generated HERE and never committed. The
#                     settings file is a credential file; ./searxng is
#                     gitignored for the same reason ci/concourse/keys is.
#   search.formats    the shipped list is `html` and nothing else, and every
#                     request for a format that is not on it is answered 403.
#                     Adding `json` is the entire difference between an
#                     instance you can browse and one a client can query.
#
# `./spectro-env up search` runs this before compose, the way it generates
# Concourse's keypairs. Running it by hand is fine and starts nothing.
#
# Re-running is safe and deliberately does NOT rotate the key: the key is this
# instance's identity, and rotating it invalidates every preferences cookie the
# instance has handed out.
set -eu
cd "$(dirname "$0")"

settings="searxng/settings.yml"

if [ -f "$settings" ]; then
  # A file from before this script, or hand-edited since, is exactly the case
  # that ends as "why does it answer 403". Refuse rather than reuse it.
  if ! grep -qE '^[[:space:]]*-[[:space:]]*json[[:space:]]*$' "$settings"; then
    echo "ci/search/$settings exists but does not list \"json\" under search.formats." >&2
    echo "That is the one setting this stack is about: SearXNG answers 403 to" >&2
    echo "format=json until it is there. Add it, or delete the file and run again." >&2
    exit 1
  fi
  exit 0
fi

command -v openssl >/dev/null 2>&1 || {
  echo "openssl is required to generate the instance secret" >&2; exit 1; }

echo "writing ci/search/$settings …"
mkdir -p searxng
umask 077
cat > "$settings" <<EOF
# Generated by ci/search/generate-settings.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# The secret key below was created on this machine and is shared with nothing.
#
# use_default_settings keeps every upstream default and overrides only what is
# written here, so a SearXNG upgrade brings its new engines along.
use_default_settings: true

server:
  # SearXNG refuses to start on the shipped placeholder.
  secret_key: "$(openssl rand -hex 32)"
  # The bot wall, off on purpose for an instance nothing outside this machine
  # can reach — the published port binds loopback. A client that sends a real
  # User-Agent and browser-shaped Accept headers passes the wall either way, so
  # turning this on later breaks nothing.
  limiter: false
  public_instance: false

search:
  # THE reason this file exists. Stock SearXNG ships this list with html and
  # nothing else, and answers HTTP 403 to every request for a format that is
  # not on it — which is every request an API client makes.
  formats:
    - html
    - json
EOF
chmod 600 "$settings"

echo "the settings are in ci/search/searxng — gitignored, and the secret key in"
echo "them is this instance's identity, so a re-run keeps it."
