#!/usr/bin/env bash
#
# Configures and starts the Langfuse stack next to this script, then hands the
# endpoint and the project keys to spectroscope.
#
# It does exactly three things, in this order:
#   1. configure  generate every secret on this machine, write ./.env (0600)
#   2. hand over  write SPECTRO_OTLP_ENDPOINT and SPECTRO_OTLP_BASIC_AUTH into
#                 ~/.spectro/.env (0600). The settings document is never touched:
#                 a pk:sk pair is a credential and belongs in the 0600 file.
#   3. start      docker compose up -d, then wait for /api/public/health
#
# Nothing in spectroscope runs this for you. The app can tell you the command;
# starting six containers is your call, made in your shell.
#
# Re-running is safe. An existing ./.env is reused as is, never rotated: the
# postgres password is baked into the volume on first boot, so a fresh password
# on a second run would lock the stack out of its own database.
#
# Usage:
#   ./install.sh                  configure, hand over, start
#   ./install.sh --configure-only configure and hand over; touch no container
#   ./install.sh --help
#
# Environment:
#   LANGFUSE_PORT          host port for the web UI      (default 3000)
#   MINIO_PORT             host port for object storage  (default 9090)
#   COMPOSE_PROJECT_NAME   compose project               (default langfuse-spectro)
#   LANGFUSE_ADMIN_EMAIL   first user's login    (default admin@spectroscope.local)
#
# The state directory is the CURRENT directory, so run this from the directory
# it lives in unless you want ./.env somewhere else.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
compose_file="$here/docker-compose.yml"
state_dir="$PWD"
env_file="$state_dir/.env"

configure_only=0
case "${1:-}" in
    --configure-only) configure_only=1 ;;
    --help|-h) sed -n '3,32p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    "") ;;
    *) echo "install.sh: unknown argument \"$1\" (try --help)" >&2; exit 2 ;;
esac

die() { echo "install.sh: $*" >&2; exit 1; }

[ -f "$compose_file" ] || die "no docker-compose.yml next to this script ($compose_file)"
command -v openssl >/dev/null 2>&1 || die "openssl is required to generate the secrets"

LANGFUSE_PORT="${LANGFUSE_PORT:-3000}"
MINIO_PORT="${MINIO_PORT:-9090}"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-langfuse-spectro}"

# ---------------------------------------------------------------- 1. configure

if [ -f "$env_file" ]; then
    echo "reusing the existing $env_file (secrets are never rotated on a re-run)"
else
    echo "generating secrets into $env_file"
    umask 077
    pk="pk-lf-$(openssl rand -hex 16)"
    sk="sk-lf-$(openssl rand -hex 24)"
    cat > "$env_file" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Every value below was
# created on this machine. Nothing here is shared with any other installation.
# Delete this file only together with the volumes (docker compose down -v), or
# the stack will hold a password this file no longer knows.
LANGFUSE_PORT=$LANGFUSE_PORT
MINIO_PORT=$MINIO_PORT
LANGFUSE_URL=http://localhost:$LANGFUSE_PORT

POSTGRES_PASSWORD=$(openssl rand -hex 32)
CLICKHOUSE_PASSWORD=$(openssl rand -hex 32)
REDIS_AUTH=$(openssl rand -hex 32)
MINIO_ROOT_USER=spectro$(openssl rand -hex 4)
MINIO_ROOT_PASSWORD=$(openssl rand -hex 32)
SALT=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)

LANGFUSE_INIT_PROJECT_PUBLIC_KEY=$pk
LANGFUSE_INIT_PROJECT_SECRET_KEY=$sk
# Measured 2026-08-02: langfuse-web validates this address and refuses to start
# at all when the domain has no dot ("Invalid environment variables:
# LANGFUSE_INIT_USER_EMAIL"). Every service stays healthy while the web
# container crash-loops, so the address needs a real shape even though nothing
# is ever sent to it.
LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_ADMIN_EMAIL:-admin@spectroscope.local}
LANGFUSE_INIT_USER_PASSWORD=$(openssl rand -hex 12)
EOF
fi
chmod 600 "$env_file"

# One value out of the generated file, without sourcing it (a .env is data, and
# sourcing data runs it).
env_value() {
    sed -n "s/^$1=//p" "$env_file" | head -n 1
}

pk="$(env_value LANGFUSE_INIT_PROJECT_PUBLIC_KEY)"
sk="$(env_value LANGFUSE_INIT_PROJECT_SECRET_KEY)"
port="$(env_value LANGFUSE_PORT)"
port="${port:-$LANGFUSE_PORT}"
[ -n "$pk" ] && [ -n "$sk" ] || die "$env_file has no project keys; delete it and run again"

# ---------------------------------------------------------------- 2. hand over

endpoint="http://localhost:$port/api/public/otel"
spectro_env="${HOME}/.spectro/.env"
mkdir -p "$(dirname "$spectro_env")"
touch "$spectro_env"
chmod 600 "$spectro_env"

# Upsert, so a second run replaces the two lines instead of appending them again.
tmp="$(mktemp "${spectro_env}.XXXXXX")"
chmod 600 "$tmp"
grep -v -E '^(SPECTRO_OTLP_ENDPOINT|SPECTRO_OTLP_BASIC_AUTH)=' "$spectro_env" > "$tmp" || true
{
    echo "SPECTRO_OTLP_ENDPOINT=$endpoint"
    echo "SPECTRO_OTLP_BASIC_AUTH=$pk:$sk"
} >> "$tmp"
mv "$tmp" "$spectro_env"
chmod 600 "$spectro_env"

echo "wrote SPECTRO_OTLP_ENDPOINT=$endpoint to $spectro_env"
echo "wrote SPECTRO_OTLP_BASIC_AUTH (not printed) to $spectro_env"

if [ "$configure_only" -eq 1 ]; then
    echo
    echo "configure only: no container was started."
    exit 0
fi

# -------------------------------------------------------------------- 3. start

case "${DOCKER_HOST:-}" in
    tcp://*|ssh://*)
        die "DOCKER_HOST points at a remote daemon (${DOCKER_HOST%%:*}://...); this stack is meant to run on this machine" ;;
esac
docker compose version >/dev/null 2>&1 \
    || die "docker compose is not available (install Docker Desktop, or the compose CLI plugin)"

echo
echo "starting six containers as project \"$COMPOSE_PROJECT_NAME\" (first run downloads several GB)"
docker compose -f "$compose_file" --env-file "$env_file" --project-directory "$state_dir" up -d

echo -n "waiting for http://localhost:$port/api/public/health "
for _ in $(seq 1 120); do
    if curl -fsS "http://localhost:$port/api/public/health" >/dev/null 2>&1; then
        echo
        echo "langfuse is up: http://localhost:$port"
        echo "log in as $(env_value LANGFUSE_INIT_USER_EMAIL); the password is in $env_file"
        echo
        echo "RESTART the spectroscope server or the desktop app now. A running JVM"
        echo "cannot re-read its environment, so the endpoint takes effect on the"
        echo "next start."
        exit 0
    fi
    echo -n "."
    sleep 2
done
echo
die "langfuse did not answer within 4 minutes. Look at: docker compose -f \"$compose_file\" --env-file \"$env_file\" logs langfuse-web"
