#!/usr/bin/env bash
#
# Starts a SearXNG instance next to this script that ANSWERS JSON, then hands
# its address to spectroscope.
#
# It does exactly three things, in this order:
#   1. configure  write ./searxng/settings.yml with a secret key generated on
#                 this machine and the json output format switched ON
#   2. start      docker compose up -d
#   3. hand over  write SPECTRO_SEARXNG_URL into ~/.spectro/.env (0600), but
#                 only after a real format=json query has come back with results
#
# Why a script and not a docker line: stock SearXNG lists only `html` under
# `search.formats`, and asks for an unlisted format are answered 403. A bare
# `docker run searxng/searxng` therefore gives a browsable search page and an
# API that hands spectroscope nothing. The settings file below is the whole
# difference, and generating a secret key per machine is the other half.
#
# Nothing in spectroscope runs this for you. The app prints the command; you
# read it and start the container.
#
# Re-running is safe. An existing ./searxng/settings.yml is reused as is: its
# secret key is this instance's identity, and rotating it on a second run would
# invalidate every preferences cookie the instance has handed out.
#
# Usage:
#   ./install.sh                  configure, start, hand over
#   ./install.sh --configure-only write the settings file; touch no container
#   ./install.sh --help
#
# Environment:
#   SEARXNG_PORT        host port           (default 8888)
#   SEARXNG_CONTAINER   container name      (default spectro-searxng)
#
# The state directory is the CURRENT directory, so run this from the directory
# it lives in unless you want ./searxng somewhere else.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
compose_file="$here/docker-compose.yml"
state_dir="$PWD"
settings_dir="$state_dir/searxng"
settings_file="$settings_dir/settings.yml"

configure_only=0
case "${1:-}" in
    --configure-only) configure_only=1 ;;
    --help|-h) sed -n '3,37p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    "") ;;
    *) echo "install.sh: unknown argument \"$1\" (try --help)" >&2; exit 2 ;;
esac

die() { echo "install.sh: $*" >&2; exit 1; }

[ -f "$compose_file" ] || die "no docker-compose.yml next to this script ($compose_file)"
command -v openssl >/dev/null 2>&1 || die "openssl is required to generate the instance secret"

SEARXNG_PORT="${SEARXNG_PORT:-8888}"
export SEARXNG_PORT
export SEARXNG_CONTAINER="${SEARXNG_CONTAINER:-spectro-searxng}"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-searxng-spectro}"

# ---------------------------------------------------------------- 1. configure

if [ -f "$settings_file" ]; then
    echo "reusing the existing $settings_file (the secret key is never rotated on a re-run)"
    # A settings file from before this script, or hand-edited since, is exactly
    # the case that ends as "why does spectroscope say 403". Say it here.
    grep -qE '^[[:space:]]*-[[:space:]]*json[[:space:]]*$' "$settings_file" || die \
        "$settings_file exists but does not list \"json\" under search.formats.
That is the one setting this whole directory is about: SearXNG answers 403 to
format=json until it is there. Add it, or delete the file and run again."
else
    echo "writing $settings_file"
    mkdir -p "$settings_dir"
    umask 077
    cat > "$settings_file" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). The secret key below
# was created on this machine and is not shared with any other installation.
#
# use_default_settings keeps every upstream default and overrides only what is
# written here, so a SearXNG upgrade brings its new engines along.
use_default_settings: true

server:
  # SearXNG refuses to start on the shipped placeholder.
  secret_key: "$(openssl rand -hex 32)"
  # The bot wall, off on purpose for an instance that only you and one local
  # program reach. spectroscope sends a real User-Agent and browser-shaped
  # Accept headers either way, so turning this on later does not break it —
  # but off is the honest default for a private instance and one less thing
  # between a paste and a working search.
  limiter: false
  public_instance: false

search:
  # THE reason this file exists. Stock SearXNG ships this list with html and
  # nothing else, and answers HTTP 403 to every request for a format that is
  # not on it — which is every request an API client makes.
  formats:
    - html
    - json
EOF
fi
chmod 600 "$settings_file"

if [ "$configure_only" -eq 1 ]; then
    echo
    echo "configure only: no container was started."
    exit 0
fi

# -------------------------------------------------------------------- 2. start

case "${DOCKER_HOST:-}" in
    tcp://*|ssh://*)
        die "DOCKER_HOST points at a remote daemon (${DOCKER_HOST%%:*}://...); this instance is meant to run on this machine, and the address handed to spectroscope below is localhost" ;;
esac
docker compose version >/dev/null 2>&1 \
    || die "docker compose is not available (install Docker Desktop, or the compose CLI plugin)"

echo
echo "starting one container as project \"$COMPOSE_PROJECT_NAME\" on port $SEARXNG_PORT"
docker compose -f "$compose_file" --project-directory "$state_dir" up -d

# ---------------------------------------------------------------- 3. hand over

url="http://localhost:$SEARXNG_PORT"

# The wait is for the ANSWER SHAPE, not for the port. A container that has
# booted with json off answers this URL instantly, with 403 — and a check that
# only asked "is it up" would call that a success and write a dead address into
# a 0600 file. So the probe is a real format=json query, and it has to come back
# as JSON carrying a results array.
echo -n "waiting for $url/search?format=json "
answered=0
for _ in $(seq 1 60); do
    body="$(curl -fsS -H 'User-Agent: Mozilla/5.0 (compatible; spectro-web-search)' \
        -H 'Accept: application/json' -H 'Accept-Encoding: gzip, deflate' --compressed \
        "$url/search?q=spectroscope&format=json" 2>/dev/null || true)"
    case "$body" in
        *'"results"'*) answered=1; break ;;
    esac
    echo -n "."
    sleep 2
done
echo

[ "$answered" -eq 1 ] || die "the instance at $url did not answer format=json within two minutes.
Look at: docker compose -f \"$compose_file\" --project-directory \"$state_dir\" logs searxng
A 403 there means settings.yml lost its \"json\" line; anything else means the
container is not up yet."

spectro_env="${HOME}/.spectro/.env"
mkdir -p "$(dirname "$spectro_env")"
touch "$spectro_env"
chmod 600 "$spectro_env"

# Upsert, so a second run replaces the line instead of appending it again.
tmp="$(mktemp "${spectro_env}.XXXXXX")"
chmod 600 "$tmp"
grep -v -E '^SPECTRO_SEARXNG_URL=' "$spectro_env" > "$tmp" || true
echo "SPECTRO_SEARXNG_URL=$url" >> "$tmp"
mv "$tmp" "$spectro_env"
chmod 600 "$spectro_env"

echo "searxng is up and answering JSON: $url"
echo "wrote SPECTRO_SEARXNG_URL=$url to $spectro_env"
echo
echo "spectroscope reads that file every time it resolves its settings, so the"
echo "next run, the next session and Settings > Web search all name this"
echo "instance — no restart, no export. Anything already running that resolved"
echo "its configuration earlier keeps the old tier until it resolves again;"
echo "restart it if 'spectro doctor' names this instance and it does not."
