// The export sheet (owner 2026-07-28: "beim export kann man kein design
// auswählen, gerne hier ein modales export view fenster mit vorschau … und dann
// design auswahl, optionen").
//
// One rule runs through every control here: an option either does what its
// label says or it is not on the sheet, and where a choice costs something the
// cost is printed NEXT TO IT, counted off this stream. An export is the one
// action whose result leaves the app entirely — nobody comes back to find out
// what was dropped, so nothing may be discovered afterwards.
//
// Three consequences worth naming, because they look like omissions:
//   - the language switcher is offered only when both languages are really in
//     hand (the text tab holds only the translated array, so it gets the
//     provenance line and no switcher);
//   - "print / save as PDF" FORCES everything expanded first, because a closed
//     <details> does not print and a PDF quietly missing every tool call is the
//     exact failure this file exists to prevent;
//   - the preview is the real document, generated by the same code as the save,
//     shown in a sandbox with SCRIPTS OFF — which it can afford, because the
//     export has no script in it. A preview needing scripts to look right would
//     be proof the export was broken.

import { useEffect, useMemo, useRef, useState } from "react";
import type { RunEvent } from "../events";
import type { Lang } from "../i18n/i18n";
import { useLang } from "../state/lang";
import { DESIGNS } from "../state/designPrefs";
import type { DesignId } from "../state/designPrefs";
import { composeDocument } from "../export/document";
import { EXPORT_THEMES } from "../export/themes";
import type { DisclosureChoice, ExportRequest, JsonlFormat, ViewId } from "../export/options";
import {
  DEFAULT_REQUEST,
  JSONL_FORMATS,
  formatLosses,
  offeredViews,
  printWouldHide,
  streamFacts,
  switcherOffer,
} from "../export/options";
import type { ExportKind } from "../export/kinds";
import { saveHtml } from "../export/html";
import "../styles/export-dialog.css";

/** Above this the preview is generated from a slice and SAYS so. Measured:
 *  chatToHtml runs 41 ms and produces 3.2 MB at 6042 events, so the cost that
 *  matters is not the string building — it is asking a browser to lay out a
 *  multi-megabyte document on every keystroke-sized option change. */
const MAX_PREVIEW_BYTES = 2_000_000;
/** How much of the stream a bounded preview shows. */
const PREVIEW_EVENTS = 1200;
/** Option changes settle before the document is rebuilt. */
const PREVIEW_DEBOUNCE_MS = 150;

const VIEW_LABEL: Record<ViewId, Record<Lang, string>> = {
  chat: { en: "chat view", de: "Chat-Ansicht" },
  text: { en: "text feed", de: "Text-Feed" },
  json: { en: "json view", de: "JSON-Ansicht" },
};

const FORMAT_LABEL: Record<JsonlFormat, Record<Lang, string>> = {
  spectroscope: { en: "spectroscope", de: "spectroscope" },
  "claude-code": { en: "Claude Code transcript", de: "Claude-Code-Transkript" },
  vscode: { en: "VS Code agent export", de: "VS-Code-Agent-Export" },
};

const bytes = (n: number, lang: Lang): string => {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)} kB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`.replace(".", lang === "de" ? "," : ".");
};

interface Preview {
  html: string;
  fullBytes: number;
  ms: number;
  bounded: boolean;
}

export interface ExportDialogProps {
  kind: ExportKind;
  /** The stream this tab renders. */
  events: readonly RunEvent[];
  /** The recorded stream when it is a DIFFERENT array from `events`; null when
   *  the caller holds only one side (see the file header). */
  original: readonly RunEvent[] | null;
  /** The translated stream when there is one. */
  translated: readonly RunEvent[] | null;
  /** The target language tag; drives the provenance line. */
  translatedTo: string | null;
  /** Units that stayed in the source language, for an honest partial note. */
  failedUnits: number;
  label?: string | null;
  extended?: boolean;
  onSaveHtml: (request: ExportRequest, html: string) => void;
  onSaveJsonl: (request: ExportRequest) => void;
  onClose: () => void;
}

export function ExportDialog(props: ExportDialogProps) {
  const lang = useLang();
  const de = lang === "de";
  const [request, setRequest] = useState<ExportRequest>(() => ({
    ...DEFAULT_REQUEST,
    kind: props.kind,
    views: [props.kind],
    primary: props.kind,
  }));
  const [preview, setPreview] = useState<Preview | null>(null);
  const printFrame = useRef<HTMLIFrameElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);

  const facts = useMemo(() => streamFacts(props.events), [props.events]);
  const losses = useMemo(() => formatLosses(request.format, facts), [request.format, facts]);
  const offer = useMemo(
    () =>
      switcherOffer({
        original: props.original,
        translated: props.translated,
        landed: props.translated === null ? 0 : 1,
        failed: props.failedUnits,
      }),
    [props.original, props.translated, props.failedUnits],
  );

  const streams = useMemo(
    () => ({
      original: props.original ?? props.events,
      translated: props.translated,
      translatedTo: props.translatedTo,
    }),
    [props.original, props.translated, props.translatedTo, props.events],
  );

  const build = (req: ExportRequest, slice?: number): string =>
    composeDocument(
      { ...req, label: props.label ?? undefined, lang, extended: props.extended },
      slice === undefined
        ? streams
        : {
            original: streams.original.slice(0, slice),
            translated: streams.translated === null ? null : streams.translated.slice(0, slice),
            translatedTo: streams.translatedTo,
          },
    );

  // Rebuild on a debounce: every option change re-renders the whole document,
  // and a reader dragging through the theme list should not pay for each stop.
  useEffect(() => {
    const timer = window.setTimeout(() => {
      const started = performance.now();
      const full = build(request);
      const ms = performance.now() - started;
      const over = full.length > MAX_PREVIEW_BYTES;
      setPreview({
        html: over ? build(request, PREVIEW_EVENTS) : full,
        fullBytes: full.length,
        ms,
        bounded: over,
      });
    }, PREVIEW_DEBOUNCE_MS);
    return () => window.clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [request, streams, lang, props.label, props.extended]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent): void => {
      if (e.key === "Escape") props.onClose();
    };
    window.addEventListener("keydown", onKey);
    dialogRef.current?.focus();
    return () => window.removeEventListener("keydown", onKey);
  }, [props]);

  const patch = (next: Partial<ExportRequest>): void => setRequest((r) => ({ ...r, ...next }));

  const toggleView = (view: ViewId): void => {
    const has = request.views.includes(view);
    // The tab the button was pressed in cannot be removed: a file with no view
    // is not an export, and silently re-adding it would be worse.
    if (has && (view === props.kind || request.views.length === 1)) return;
    const views = offeredViews(props.kind).filter((v) => (v === view ? !has : request.views.includes(v)));
    patch({ views, primary: views.includes(request.primary) ? request.primary : views[0] });
  };

  const saveTheHtml = (): void => {
    props.onSaveHtml(request, build(request));
    props.onClose();
  };

  const print = (): void => {
    // Everything expanded, whatever the sheet says: closed cards do not print.
    // The reader is told this on the button, so the difference is not a
    // surprise when the PDF comes out longer than the preview.
    const expanded: ExportRequest = { ...request, reasoning: "open", tools: "open" };
    const frame = printFrame.current;
    if (frame === null) return;
    frame.srcdoc = build(expanded);
    frame.onload = () => {
      frame.contentWindow?.focus();
      frame.contentWindow?.print();
    };
  };

  const themeName = (id: DesignId): string => EXPORT_THEMES.find((t) => t.id === id)?.name[lang] ?? id;

  return (
    <div className="xd-backdrop" onMouseDown={(e) => e.target === e.currentTarget && props.onClose()}>
      <div
        className="xd-modal"
        role="dialog"
        aria-modal="true"
        aria-label={de ? "Export" : "Export"}
        ref={dialogRef}
        tabIndex={-1}
      >
        <div className="xd-head">
          <h2 className="xd-title">{de ? "Exportieren" : "Export"}</h2>
          <span className="xd-sub">
            {props.events.length} {de ? "Events" : "events"}
          </span>
          <button type="button" className="ghost xd-close" onClick={props.onClose}>
            {de ? "Schließen" : "Close"}
          </button>
        </div>

        <div className="xd-body">
          <div className="xd-options">
            {/* ---- views ---- */}
            <fieldset className="xd-group">
              <legend className="xd-legend">{de ? "Ansichten" : "Views"}</legend>
              {offeredViews(props.kind).map((view) => {
                const locked = view === props.kind;
                return (
                  <label key={view} className={`xd-row${locked ? " xd-row--disabled" : ""}`}>
                    <input
                      type="checkbox"
                      checked={request.views.includes(view)}
                      disabled={locked}
                      onChange={() => toggleView(view)}
                    />
                    <span>
                      <span className="xd-name">{VIEW_LABEL[view][lang]}</span>
                      {view === "json" && (
                        <span className="xd-hint">
                          {de
                            ? "wie im Text-Tab — reine Socket-Frames fehlen"
                            : "as the text tab shows it — socket-only frames omitted"}
                        </span>
                      )}
                      {locked && (
                        <span className="xd-hint">
                          {de ? "die Ansicht, aus der du exportierst" : "the view you are exporting from"}
                        </span>
                      )}
                    </span>
                  </label>
                );
              })}
            </fieldset>

            {/* ---- theme ---- */}
            <fieldset className="xd-group">
              <legend className="xd-legend">{de ? "Design" : "Theme"}</legend>
              {DESIGNS.map((design) => (
                <label key={design.id} className="xd-row">
                  <input
                    type="radio"
                    name="xd-theme"
                    checked={request.theme === design.id}
                    onChange={() => patch({ theme: design.id })}
                  />
                  <span className="xd-name">{themeName(design.id)}</span>
                </label>
              ))}
            </fieldset>

            {/* ---- disclosure ---- */}
            <fieldset className="xd-group">
              <legend className="xd-legend">{de ? "Aufgeklappt" : "Expanded"}</legend>
              {(
                [
                  ["tools", de ? "Tool-Karten" : "tool cards"],
                  ["reasoning", de ? "Denken" : "reasoning"],
                ] as ReadonlyArray<["tools" | "reasoning", string]>
              ).map(([key, name]) => (
                <label key={key} className="xd-row">
                  <input
                    type="checkbox"
                    checked={request[key] === "open"}
                    onChange={(e) =>
                      patch({ [key]: (e.target.checked ? "open" : "collapsed") as DisclosureChoice })
                    }
                  />
                  <span className="xd-name">{name}</span>
                </label>
              ))}
              {printWouldHide(request) && (
                <p className="xd-loss">
                  {de
                    ? "Zugeklappte Karten drucken nicht mit. Der Druck-Knopf klappt deshalb vorher alles auf."
                    : "Collapsed cards do not print. The print button expands everything first."}
                </p>
              )}
            </fieldset>

            {/* ---- language ---- */}
            {props.translatedTo !== null && (
              <fieldset className="xd-group">
                <legend className="xd-legend">{de ? "Sprache" : "Language"}</legend>
                <label className={`xd-row${offer.offered ? "" : " xd-row--disabled"}`}>
                  <input
                    type="checkbox"
                    checked={request.switcher && offer.offered}
                    disabled={!offer.offered}
                    onChange={(e) => patch({ switcher: e.target.checked })}
                  />
                  <span>
                    <span className="xd-name">
                      {de ? "Sprachumschalter in die Datei" : "language switcher in the file"}
                    </span>
                    <span className="xd-hint">
                      {offer.offered
                        ? de
                          ? `beide Sprachen in einer Datei, umschaltbar ohne Skript (Original und ${props.translatedTo})`
                          : `both languages in one file, switched without script (original and ${props.translatedTo})`
                        : de
                          ? "diese Ansicht hält nur die Übersetzung — die Datei sagt, dass sie eine ist"
                          : "this view holds only the translation — the file says that it is one"}
                    </span>
                    {offer.partial > 0 && (
                      <span className="xd-hint">
                        {de
                          ? `${offer.partial} Abschnitte blieben in der Originalsprache`
                          : `${offer.partial} passages stayed in the original language`}
                      </span>
                    )}
                  </span>
                </label>
              </fieldset>
            )}

            {/* ---- jsonl format ---- */}
            <fieldset className="xd-group">
              <legend className="xd-legend">{de ? "JSONL-Format" : "JSONL format"}</legend>
              {JSONL_FORMATS.map((format) => (
                <label key={format} className="xd-row">
                  <input
                    type="radio"
                    name="xd-format"
                    checked={request.format === format}
                    onChange={() => patch({ format })}
                  />
                  <span className="xd-name">{FORMAT_LABEL[format][lang]}</span>
                </label>
              ))}
              {losses.length === 0 ? (
                <p className="xd-lossless">{de ? "nichts geht verloren" : "nothing is lost"}</p>
              ) : (
                <div className="xd-loss">
                  <ul>
                    {losses.map((loss) => (
                      <li key={loss.code}>{de ? loss.de : loss.en}</li>
                    ))}
                  </ul>
                </div>
              )}
            </fieldset>
          </div>

          {/* ---- preview ---- */}
          <div className="xd-preview-wrap">
            <div className="xd-preview-bar">
              <span>{de ? "Vorschau" : "preview"}</span>
              {preview !== null && (
                <>
                  <span>{bytes(preview.fullBytes, lang)}</span>
                  <span>{preview.ms.toFixed(0)} ms</span>
                  {preview.bounded && (
                    <span className="xd-bounded">
                      {de
                        ? `zeigt die ersten ${PREVIEW_EVENTS} Events — die Datei trägt alle ${props.events.length}`
                        : `showing the first ${PREVIEW_EVENTS} events — the file carries all ${props.events.length}`}
                    </span>
                  )}
                </>
              )}
            </div>
            {/* sandbox="" — no scripts, no same-origin. The export has no script
                in it, so the preview is faithful with the whole engine off. */}
            <iframe
              className="xd-frame"
              sandbox=""
              srcDoc={preview?.html ?? ""}
              title={de ? "Vorschau des Exports" : "export preview"}
            />
          </div>
        </div>

        <div className="xd-foot">
          <span className="xd-foot-note">
            {de
              ? "Die Datei öffnet ohne Netz: alles liegt darin."
              : "The file opens offline: everything is inside it."}
          </span>
          <div className="xd-actions">
            <button type="button" className="ghost" onClick={print}>
              {de ? "Drucken / als PDF" : "Print / save as PDF"}
            </button>
            <button type="button" className="ghost" onClick={() => props.onSaveJsonl(request)}>
              {de ? "JSONL speichern" : "Save JSONL"}
            </button>
            <button type="button" onClick={saveTheHtml}>
              {de ? "HTML speichern" : "Save HTML"}
            </button>
          </div>
        </div>

        {/* The print document is built fresh and fully expanded; allow-modals is
            what lets a sandboxed frame open the print dialog, and same-origin is
            what lets this window call into it. Scripts stay off. */}
        <iframe
          className="xd-print-frame"
          ref={printFrame}
          sandbox="allow-same-origin allow-modals"
          title="print"
        />
      </div>
    </div>
  );
}

/** Re-exported so the menu can hand the same saver to the dialog and to itself. */
export { saveHtml };
