package dev.spectroscope.core.config.governing;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.Comparator;
import java.util.List;

/**
 * The registry of numbers that govern a run — the read side of card 357.
 *
 * <p><b>Nothing here is typed.</b> The list is a resource generated by
 * {@code GoverningScan} from the source tree: it walks
 * {@code spectro-core/src/main/java} for numeric {@code static final}s, takes
 * the classification off each one's {@link Governs} annotation, reads the live
 * value off the field, and lifts the explanation from the javadoc already
 * standing above it. {@code GoverningNumbersDriftTest} regenerates that scan
 * on every run and fails when this resource disagrees with the source by one
 * constant, one value or one word — so a 77th constant cannot ship without
 * appearing here, and a number that moves cannot leave a stale value behind on
 * the settings room.</p>
 *
 * <p>The resource exists because a javadoc is not in the bytecode. Reflection
 * alone would give the values and the kinds and lose every explanation, which
 * is exactly the reach the card was cut to fix.</p>
 */
public final class GoverningNumbers {

    /** Where the generated registry sits on the classpath. The scan writes
     *  this file and the drift test holds it to the source. */
    public static final String RESOURCE = "/governing/numbers.json";

    private static final List<GoverningNumber> ALL = load();

    private GoverningNumbers() {
    }

    /**
     * Every classified numeric constant, governing or not, ordered by
     * declaring class and then by name — the order the resource is generated
     * in, so two readers of the same build see the same page.
     *
     * @return the whole registry, unmodifiable
     */
    public static List<GoverningNumber> all() {
        return ALL;
    }

    /**
     * The ones that govern a run: everything except the aliases and the
     * plumbing. The exclusion is {@link Governs.Kind#governs()} and nothing
     * else — no name list, no second definition.
     *
     * @return the governing numbers, unmodifiable
     */
    public static List<GoverningNumber> governing() {
        return ALL.stream().filter(GoverningNumber::governs).toList();
    }

    private static List<GoverningNumber> load() {
        try (InputStream in = GoverningNumbers.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(RESOURCE + " is missing from the jar —"
                        + " the generated registry is part of the build, not an optional extra");
            }
            List<GoverningNumber> read = new ObjectMapper()
                    .readValue(in, new TypeReference<List<GoverningNumber>>() { });
            return read.stream()
                    .sorted(Comparator.comparing(GoverningNumber::owner)
                            .thenComparing(GoverningNumber::field))
                    .toList();
        } catch (IOException e) {
            throw new UncheckedIOException("cannot read " + RESOURCE, e);
        }
    }
}
