import type { LangDef } from "./spec";

const KEYWORDS: ReadonlySet<string> = new Set([
  "if",
  "then",
  "else",
  "elif",
  "fi",
  "for",
  "while",
  "until",
  "do",
  "done",
  "case",
  "esac",
  "in",
  "function",
  "select",
  "return",
  "break",
  "continue",
  "local",
  "export",
  "declare",
  "readonly",
  "source",
  "set",
  "unset",
  // The commands themselves. A shell transcript is read for WHAT IT DID, so the
  // verb at the head of a line carries more meaning than the control keyword —
  // and a session that greps a compromised host is all verbs and no `if`.
  "cat",
  "cd",
  "chmod",
  "chown",
  "cp",
  "curl",
  "cut",
  "df",
  "diff",
  "du",
  "echo",
  "find",
  "grep",
  "head",
  "kill",
  "ln",
  "ls",
  "mkdir",
  "mv",
  "printf",
  "ps",
  "pwd",
  "rm",
  "rmdir",
  "scp",
  "sed",
  "sort",
  "ssh",
  "stat",
  "sudo",
  "tail",
  "tar",
  "tee",
  "touch",
  "tr",
  "uniq",
  "wc",
  "wget",
  "which",
  "xargs",
  "zip",
  "unzip",
  "awk",
  "git",
  "npm",
  "node",
  "python",
  "python3",
  "pip",
  "java",
  "docker",
  "systemctl",
  "service",
  "mysql",
  "psql",
  "sqlite3",
  "openssl",
  "rsync",
  "nohup",
  "exec",
  "eval",
  "test",
  "sleep",
  "date",
  "env",
  "expect",
  "spawn",
  "send",
]);

export const shell: LangDef = {
  // `console` is here because a transcript pasted from a terminal is fenced that
  // way as often as it is fenced `sh`.
  aliases: ["sh", "bash", "zsh", "shell", "console"],
  extensions: ["sh", "bash", "zsh"],
  spec: { line: ["#"], quotes: ['"', "'"], keywords: KEYWORDS },
};
