import type { LangDef } from "./spec";

const KEYWORDS: ReadonlySet<string> = new Set([
  "select",
  "from",
  "where",
  "insert",
  "into",
  "values",
  "update",
  "set",
  "delete",
  "create",
  "alter",
  "drop",
  "table",
  "index",
  "view",
  "database",
  "schema",
  "join",
  "inner",
  "left",
  "right",
  "outer",
  "full",
  "cross",
  "on",
  "using",
  "group",
  "order",
  "by",
  "having",
  "limit",
  "offset",
  "union",
  "all",
  "distinct",
  "as",
  "and",
  "or",
  "not",
  "null",
  "is",
  "in",
  "like",
  "between",
  "exists",
  "case",
  "when",
  "then",
  "else",
  "end",
  "count",
  "sum",
  "avg",
  "min",
  "max",
  "primary",
  "foreign",
  "key",
  "references",
  "constraint",
  "unique",
  "default",
  "begin",
  "commit",
  "rollback",
  "transaction",
  "grant",
  "revoke",
  "with",
  "asc",
  "desc",
  "true",
  "false",
  "if",
  "add",
  "column",
  "rename",
  "truncate",
]);

export const sql: LangDef = {
  // The dialect names all resolve to one spec: the differences between them live
  // in functions and types, not in the comment, string and keyword forms this
  // module colours.
  aliases: ["sql", "mysql", "postgres", "postgresql", "sqlite"],
  extensions: ["sql"],
  // SQL keywords are conventionally written upper-case, so the lookup folds case.
  spec: { line: ["--"], block: ["/*", "*/"], quotes: ["'", '"'], keywords: KEYWORDS, foldCase: true },
};
